#!/bin/sh

echo "Running Code Sniffer..."
docker exec app composer phpcs
if [ $? != 0 ]
then
    echo "Coding standards errors have been detected. Running phpcbf..."
    docker exec app composer phpcbf

    echo "Running Code Sniffer again..."
    docker exec app composer phpcs
    if [ $? != 0 ]
    then
        echo "Fix errors to commit"
        exit 1
    fi
fi

echo "Running Tests..."
docker exec app ./vendor/bin/phpunit --stop-on-failure
if [ $? != 0 ]
then
    echo "Fix errors to commit"
    exit 1
fi