FROM nginx:alpine

COPY . /var/www/laravel-app
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf.template

EXPOSE 80

COPY ./docker/entrypoint.nginx.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
